name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build Project
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        build-type: [Debug, Release]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: lukka/get-cmake@v4
    - uses: KyleMayes/install-llvm-action@v2
      with:
        version: "21"
    - run: |
        mkdir build
        cd build
        cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=${{matrix.build-type}} ..
        cmake --build .